version: '3.8'

networks:
  tradie-network:
    driver: bridge

services:
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - account-service
      - tradie-service
      - booking-service
      - review-service
      - notification-service
    networks:
      - tradie-network

  message-broker:
    image: rabbitmq:3.9-management-alpine
    container_name: message-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tradie-network

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    depends_on:
      - message-broker
      - notification-db
    environment:
      - DB_HOST=notification-db
      - DB_PORT=3306
      - DB_NAME=notification
      - DB_USER=root
      - DB_PASSWORD=root
      - RABBITMQ_URL=amqp://guest:guest@message-broker:5672
    networks:
      - tradie-network

  notification-db:
    image: mysql:8
    container_name: notification-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: notification
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - notification-db-data:/var/lib/mysql
    networks:
      - tradie-network

  booking-db:
    image: mysql:8
    container_name: booking-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: booking_db
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "3308:3306"
    volumes:
      - booking-db-data:/var/lib/mysql
    networks:
      - tradie-network

  # account-service:
  #   build: ./services/account-service
  #   container_name: account-service
  #   networks:
  #     - tradie-network

  # tradie-service:
  #   build: ./services/tradie-service
  #   container_name: tradie-service
  #   networks:
  #     - tradie-network


  booking-service:
    build: ./services/booking-service
    container_name: booking-service
    depends_on:
      - booking-db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=booking-db
      - DB_PORT=3306
      - DB_DATABASE=booking_db
      - DB_USERNAME=your_user
      - DB_PASSWORD=your_password
    networks:
      - tradie-network

  review-service:
    build: ./services/review-service
    container_name: review-service
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@review-db:3306/review_db
    ports:
      - "8001:8000"
    networks:
      - tradie-network
    depends_on:
      - review-db

  review-db:
    image: mysql:8.0
    container_name: review-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=review_db
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
      - MYSQL_ROOT_PASSWORD=your_root_password
    ports:
      - "3309:3306"
    volumes:
      - review-db-data:/var/lib/mysql
    networks:
      - tradie-network

  account-db:
    image: mysql:8.0
    container_name: account-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=account_db
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
      - MYSQL_ROOT_PASSWORD=your_root_password
    ports:
      - "3310:3306"
    volumes:
      - account-db-data:/var/lib/mysql
    networks:
      - tradie-network

  account-service:
    build: ./services/account-service
    container_name: account-service
    depends_on:
      - account-db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=account-db
      - DB_PORT=3306
      - DB_DATABASE=account_db
      - DB_USERNAME=your_user
      - DB_PASSWORD=your_password
    networks:
      - tradie-network

  tradie-db:
    image: mysql:8.0
    container_name: tradie-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=tradie_db
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
      - MYSQL_ROOT_PASSWORD=your_root_password
    ports:
      - "3311:3306"
    volumes:
      - tradie-db-data:/var/lib/mysql
    networks:
      - tradie-network

  tradie-service:
    build: ./services/tradie-service
    container_name: tradie-service
    depends_on:
      - tradie-db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=tradie-db
      - DB_PORT=3306
      - DB_DATABASE=tradie_db
      - DB_USERNAME=your_user
      - DB_PASSWORD=your_password
    networks:
      - tradie-network

volumes:
  notification-db-data:
  booking-db-data:
  review-db-data:
  account-db-data:
  tradie-db-data:
