version: '3.8'

networks:
  tradie-network:
    driver: bridge

services:
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - account-service
      - tradie-service
      - booking-service
      - review-service
      - notification-service
    networks:
      - tradie-network

  message-broker:
    image: rabbitmq:3.9-management-alpine
    container_name: message-broker
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "15672:15672"
    networks:
      - tradie-network

  websocket-service:
    build: ./services/websocket-service
    container_name: websocket-service
    depends_on:
      - message-broker
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
    ports:
      - "4000:4000"
    networks:
      - tradie-network

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    depends_on:
      - message-broker
      - notification-db
    environment:
      - DB_HOST=notification-db
      - DB_PORT=3306
      - DB_NAME=${NOTIFICATION_MYSQL_DATABASE}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
    networks:
      - tradie-network

  notification-db:
    image: mysql:8
    container_name: notification-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${NOTIFICATION_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    ports:
      - "${NOTIFICATION_DB_PORT:-3307}:3306"
    volumes:
      - notification-db-data:/var/lib/mysql
    networks:
      - tradie-network

  booking-db:
    image: mysql:8.0
    container_name: booking-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${BOOKING_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    ports:
      - "${BOOKING_DB_PORT:-3308}:3306"
    volumes:
      - booking-db-data:/var/lib/mysql
    networks:
      - tradie-network

  # account-service:
  #   build: ./services/account-service
  #   container_name: account-service
  #   networks:
  #     - tradie-network

  # tradie-service:
  #   build: ./services/tradie-service
  #   container_name: tradie-service
  #   networks:
  #     - tradie-network


  booking-service:
    build: ./services/booking-service
    container_name: booking-service
    depends_on:
      - booking-db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=booking-db
      - DB_PORT=3306
      - DB_DATABASE=${BOOKING_MYSQL_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ACCOUNT_SERVICE_URL=http://account-service:${ACCOUNT_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - tradie-network

  review-service:
    build: ./services/review-service
    container_name: review-service
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://${DB_USERNAME}:${DB_PASSWORD}@review-db:3306/${REVIEW_MYSQL_DATABASE}
    ports:
      - "8001:8000"
    networks:
      - tradie-network
    depends_on:
      - review-db

  review-db:
    image: mysql:8.0
    container_name: review-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${REVIEW_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    ports:
      - "${REVIEW_DB_PORT:-3309}:3306"
    volumes:
      - review-db-data:/var/lib/mysql
    networks:
      - tradie-network

  account-db:
    image: mysql:8.0
    container_name: account-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${ACCOUNT_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    ports:
      - "${ACCOUNT_DB_PORT:-3310}:3306"
    volumes:
      - account-db-data:/var/lib/mysql
    networks:
      - tradie-network

  account-service:
    build: ./services/account-service
    container_name: account-service
    depends_on:
      - account-db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=account-db
      - DB_PORT=3306
      - DB_DATABASE=${ACCOUNT_MYSQL_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - tradie-network

  tradie-db:
    image: mysql:8.0
    container_name: tradie-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${TRADIE_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    ports:
      - "${TRADIE_DB_PORT:-3311}:3306"
    volumes:
      - tradie-db-data:/var/lib/mysql
    networks:
      - tradie-network

  tradie-service:
    build: ./services/tradie-service
    container_name: tradie-service
    depends_on:
      - tradie-db
    ports:
      - "${TRADIE_SERVICE_PORT:-3000}:3000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=tradie-db
      - DB_PORT=3306
      - DB_DATABASE=${TRADIE_MYSQL_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - tradie-network

  tradie-worker:
    build: ./services/tradie-service
    container_name: tradie-worker
    restart: unless-stopped
    command: php artisan ratings:listen
    depends_on:
      - tradie-db
      - message-broker
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=tradie-db
      - DB_PORT=3306
      - DB_DATABASE=${TRADIE_MYSQL_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - tradie-network

volumes:
  notification-db-data:
  booking-db-data:
  review-db-data:
  account-db-data:
  tradie-db-data:
