version: '3.8'

networks:
  tradie-network:
    driver: bridge

services:
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    # depends_on:
    #   - account-service
    #   - tradie-service
    #   - booking-service
    #   - review-service
    networks:
      - tradie-network

  message-broker:
    image: rabbitmq:3.9-management-alpine
    container_name: message-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tradie-network

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    command: php artisan listen:notifications
    depends_on:
      - message-broker
      - notification-db
    environment:
      - DB_HOST=notification-db
      - MESSAGE_BROKER_HOST=message-broker
    networks:
      - tradie-network

  notification-db:
    image: mysql:8
    container_name: notification-db
    environment:
      MYSQL_DATABASE: notification
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - tradie-network

  # account-service:
  #   build: ./services/account-service
  #   container_name: account-service
  #   networks:
  #     - tradie-network

  # tradie-service:
  #   build: ./services/tradie-service
  #   container_name: tradie-service
  #   networks:
  #     - tradie-network

  # booking-service:
  #   build: ./services/booking-service
  #   container_name: booking-service
  #   networks:
  #     - tradie-network

  # review-service:
  #   build: ./services/review-service
  #   container_name: review-service
  #   networks:
  #     - tradie-network
